import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { auth } from "@/utils/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  const session = await auth()
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar session={session}/>
          {children}
      </body>
    </html>
  );
}
